# Generated by Django 2.2.3 on 2019-07-28 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(null=True, upload_to='backgrounds'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaderboard.Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons'),
        ),
    ]
