# Generated by Django 2.2.3 on 2019-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190727_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='background_color',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
