# Generated by Django 2.2.3 on 2019-08-03 14:10

from django.db import migrations
from api.users.documents import UserDocument


def create_es_mapping(apps, schema_editor):
    UserDocument.init()


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20190727_2339")]

    operations = [migrations.RunPython(create_es_mapping, migrations.RunPython.noop)]
