# Generated by Django 2.2.3 on 2019-08-04 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournaments.Tournament'),
        ),
        migrations.AlterField(
            model_name='playergame',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Team'),
            preserve_default=False,
        ),
    ]
